name: Generate GitHub Metrics

permissions:
  contents: write

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Base config ---
          user: 0vertake
          repositories_affiliations: owner, collaborator, organization_member, contributed
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Belgrade
          config_display: large

          # --- Plugins ---
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_other: yes
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 365

          plugin_followup: yes        # adds stars/forks/followers summary
          plugin_stars: yes           # shows starred repos
          plugin_achievements: yes    # small badges for contributions
          plugin_isocalendar: yes     # contribution calendar

          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugins_errors_fatal: no    # <- corrected here
